# Generated by Django 3.0.7 on 2020-06-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='phonenumber',
            field=models.CharField(max_length=11, null=True, verbose_name='전화번호'),
        ),
    ]
