# Generated by Django 3.0.7 on 2020-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeID', '0003_id_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id',
            name='id',
        ),
        migrations.AlterField(
            model_name='id',
            name='anonymousID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Token'),
        ),
    ]
