# Generated by Django 3.0.7 on 2020-06-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=30, verbose_name='Token')),
                ('store_name', models.CharField(max_length=100, verbose_name='이름')),
                ('geolat', models.FloatField(max_length=11, verbose_name='위도')),
                ('geolon', models.FloatField(max_length=11, verbose_name='경도')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'store',
                'db_table': 'Store',
            },
        ),
    ]
