# Generated by Django 3.0.7 on 2020-06-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=30, verbose_name='Token'),
        ),
    ]
