# Generated by Django 3.0.7 on 2020-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_auto_20200608_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=30, verbose_name='가게 code'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=100, verbose_name='가게 이름'),
        ),
    ]
