# Generated by Django 3.0.7 on 2020-06-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0003_auto_20200608_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='geolat',
            field=models.CharField(max_length=11, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='store',
            name='geolon',
            field=models.CharField(max_length=11, verbose_name='경도'),
        ),
    ]
