# Generated by Django 3.0.7 on 2020-06-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0004_auto_20200608_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='geolat',
            field=models.DecimalField(decimal_places=14, max_digits=20, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='store',
            name='geolon',
            field=models.DecimalField(decimal_places=14, max_digits=20, verbose_name='경도'),
        ),
    ]
