# Generated by Django 3.0.7 on 2020-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0005_auto_20200608_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='가게 code'),
        ),
    ]
